version: '3.8'
services:
  senderapp:
    image: traffic
    container_name: traffic    
    ports:
      - "8092:8092"
    environment:
       - SPRING_RABBITMQ_HOST=rabbitmq 
    depends_on:
      - rabbitmq
  listnerapp:
    image: trafficdashboard
    container_name: trafficdashboard   
    ports:
      - "8094:8094"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq 
    depends_on:
      - rabbitmq
      - senderapp      
  rabbitmq:
    image: rabbitmq 
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
